### ISSUE TITLE
KeyError with empty choice

### ISSUE THREAD

**Issue by Rangababu-R** [open-traffic-generator/openapiart#364] opened 2022-09-07 03:25 UTC
```yaml
        "functions": [
          { 
            "choice": "connect_arp"
          }
        ],
```

```python
self = <dash_model.FunctionIter object at 0x7efca541a280>, key = 0
    def _getitem(self, key):
        found = None
        if isinstance(key, int):
            found = self._items[key]
        elif isinstance(key, slice) is True:
            start, stop, step = key.indices(len(self))
            sliced = self.__class__()
            for i in range(start, stop, step):
                sliced._items.append(self._items[i])
            return sliced
        elif isinstance(key, str):
            for item in self._items:
                if item.name == key:
                    found = item
        if found is None:
            raise IndexError()
        if (
            self._GETITEM_RETURNS_CHOICE_OBJECT is True
            and found._properties.get("choice") is not None
        ):
>           return found._properties[found._properties["choice"]]
E           KeyError: 'connect_arp'
artifacts/dash_model/dash_model/dash_model.py:745: KeyError
```

**Comment by Rangababu-R** [comment] 2022-09-07 03:28
@lyle-thompson-keysight Could you please provide the model spec. I suspect the model spec could have an issue.

As per the openapiart there shall be a property defined with in the class of all the choice enums.
If you provide the model spec I could evaluate more on this issue.

**Comment by lyle-thompson-keysight** [comment] 2022-09-07 15:08
OK, I do have an enum where I don't have properties defined within the class. How do I model a choice with no properties? Just because you make it a rule in the guide doesn't mean it's not a bug. It's just covering up the bug of failing to support regular enums like that supported in all modern programming languages. Also, if this is a rule, then your "tool" should verify it and throw an error and refuse to parse the model.

**Comment by Rangababu-R** [comment] 2022-09-08 05:09
Yes, I agree that its a bug and that is why we created this issue. If the model spec is not as per the rule the bundler shall raise an exception which is not happening now. Thanks for providing the info. we will fix rule at model validation.

**Comment by ashutshkumr** [comment] 2022-11-11 12:36
Duplicate of https://github.com/open-traffic-generator/openapiart/issues/365

**Closed by ashutshkumr** 2022-11-11 12:36 UTC
