### ISSUE TITLE
Cannot extract individual row from fetched metrics

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/openapiart#132] opened 2021-08-24 14:23 UTC
In snippet below, from snappi SDK, I'm not able to extract device-specific metric from response.

```go
		req := api.NewMetricsRequest()
		req.Bgpv4()
		for i := 0; i < 10; i++ {
			res, err := api.GetMetrics(req)
			if err != nil {
				log.Fatal(err)
			}

			// TODO: cannot extract further from response
			log.Println(res)
		}
```

**Comment by ajbalogh** [comment] 2021-08-24 14:24
duplicate of issue #111

**Closed** 2021-08-30 23:53 UTC
Labels: bug, go ux sdk gen
